In [5]:
import numpy as np

def create_design_matrix(n_order, x):
    """Transforms a feature vector into a design matrix 
    (nth order polynomial).
    
    Parameters
    ----------
    n_order : int
        Order of the polynomial.
    x : 1-d Numpy array
        Feature vector.
    """
    dmatrix = np.empty(shape=(x.shape[0], n_order))
    for i in range(len(x)):
        for j in range(n_order):
            dmatrix[i, j] = x[i] ** (j+1)
    return dmatrix

In [9]:
x = np.array([1,2,3])
print(x.shape)
xt = create_design_matrix(5,x)
print(xt.shape)
print(xt)

(3,)
(3, 5)
[[  1.   1.   1.   1.   1.]
 [  2.   4.   8.  16.  32.]
 [  3.   9.  27.  81. 243.]]
